project:
  type: book
  output-dir: _book

book:
  title: "DSViz: Listas enlazadas"
  subtitle: "Versión 1.0: Visualización e interacción con listas enlazadas"
  author: 
    - name: "Gustavo Gutiérrez-Sabogal"
      email: "gustavo.gutierrez@utp.edu.co"
    - name: "Jovanny Bedoya-Guapacha"
      email: "jovan@utp.edu.co"
    - name: "Nancy Janet Castillo-Rodríguez"
      email: "nancycastillo@utp.edu.co"


  date: "today"
  
  search: true
  
  # Navigation structure (Sidebar)
  sidebar:
    style: docked
    collapse-level: 2
  
  chapters:
    - index.qmd
    - funcionalidad.qmd
    - operaciones.qmd
    - futuro.qmd

lang: es 

#bibliography: references.bib

format:
  html:
    theme: cosmo       # Other options: flatly, journal, litera, etc.
    code-copy: true    # Adds a copy button to code blocks
    toc: true          # Table of contents on the right
    toc-depth: 3
    number-sections: true
    smooth-scroll: true

#  typst:
#    toc: true
#    number-sections: true

  typst:
    papersize: us-letter
    toc: true
    lof: true
    number-sections: true
    colorlinks: true